# Generated by Django 4.2.6 on 2023-12-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='Puss_in_boots.jpg', null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
